[package]
name = "dm_stutter"
version = "0.1.0"
authors = ["davemollen <davemollen@gmail.com>"]
edition = "2021"

[dependencies]
lv2 = "0.6.0"
stutter = { path = "../stutter" }

[lib]
crate-type = ["cdylib"]